import java.util.Scanner;
public class Akash
{
    public static void main(String args[])
    {
        Scanner sc=new Scanner(System.in);
        System.out.println("Enter the number 1");
        int a=sc.nextInt();
         System.out.println("Enter the number 1");
        int b=sc.nextInt();
        
        try            
        {
            int x[]={12,23,34,45,0};
            try
            {
                 int c=a/b;
            System.out.println("c="+c);                                   // if the this exception is occer then next line exception not working 
            }
           catch(ArithmeticException e)
            {
             System.out.println("It is divide by Zero"+e);                  //   nested try catch block
            }
        
            System.out.println("x[5]="+x[5]);                                    //one of them is working working goto to the catch block
        }
        catch(Exception e)
          {
            System.out.println("Exception in array"+e);                                
           }
       
        
        System.out.println("Bye");
    }
}
